### ISSUE TITLE
How to use in a portable Xamarin.Forms project?

### ISSUE THREAD

**Issue by rgyorodi** [picolyl/XamarinPlugins.PCLSpecialFolder#1]
Can this be used in a portable Xamarin.Forms project or only in a shared one? If yes how?

The PCLStorage plugin can be installed into a portable project and it works as long as it is also referenced in the platform specific projects too.

Unfortunately when I try to install PCLSpecialFolder into the portable project it gives an error regarding the FolderPath dependency:

> Could not install package 'FolderPath 1.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I tried this in a newly created **Blank Xaml App (Xamarin.Forms Portable)** project in Visual Studio Enterprise 2015 with all the latest updates applied.

Any suggestions?

**Comment by picolyl** [comment]
PCLSpecialFolder does not support Silverlight.
If your project include [Windows Phone Silverlight 8] , delete it and try again.

http://stackoverflow.com/questions/35041291/remove-ios-windows8-and-wp8-from-xamarin-forms-pcl-nuget-3-0-opt-into-error
https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/

**Comment by rgyorodi** [comment]
Sorry for the delay in closing this.
Thanks for the tip. It worked. I had to remove every package and then re-add them into the remaining projects. Good job.
